### PR TITLE
Add a Note about ES6 Object.assign now present in Node.js >= 4

### PR DESCRIPTION
**Pull request by madarche**
Since Node.js >= 4, [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) now offers the same functionality natively. See [ECMAScript 2015 (ES6) in Node.js](https://nodejs.org/en/docs/es6)

### CODE REVIEW

**Comment by ljharb** [comment]
According to my https://www.npmjs.com/package/object.assign tests, node 4 has 9 test failures, and node 5 has 8. Native support isn't the same thing as compliant native support.

This note should indicate a) that `Object.assign` does not offer "deep extend" functionality, and that b) the native implementations of `Object.assign` in both node and many browsers (since npm modules are for the browser too) are not fully spec-compliant. It'd be nice to also point at the `object.assign` module for a compliant replacement.

**Comment by madarche** [comment]
Thanks very much @ljharb I'll modify the PR. `Object.assign` in Node.js is working for my usages, I haven't done a compliant native support full review.

**Comment by ljharb** [comment]
(as to the test failures, a rebase on the latest master will fix those, they're obviously unrelated to this PR)

**Comment by madarche** [comment]
Please @ljharb what do you think of this PR now?

**Comment by ljharb** [comment]
@madarche Thanks! If you could condense these down to 1 commit I'll merge it straight away

**Comment by madarche** [comment]
@ljharb done as you requested

**Pull request merged**
